
posicao = int(input(" Digite a sua posição: "))

if posicao == 8:
    pontos = 1
    print(f"Você ganhou {pontos} pontos")

elif posicao == 7:
    pontos = 2
    print(f"Você ganhou {pontos} pontos")

elif posicao == 6:
    pontos = 3
    print(f"Você ganhou {pontos} pontos")

elif posicao == 5:
    pontos = 4
    print(f"Você ganhou {pontos} pontos")

elif posicao == 4:
    pontos = 5
    print(f"Você ganhou {pontos} pontos")

elif posicao == 3:
    pontos = 6
    print(f"Você ganhou {pontos} pontos")

elif posicao == 2:
    pontos = 8
    print(f"Você ganhou {pontos} pontos")

elif posicao == 1:
    pontos = 10
    print(f"Você ganhou {pontos} pontos")

else:
    print("Você não ganhou pontos") 

